version: "2"

services:
  nexus:
    image: novinrepo:8082/docker/sonatype/nexus3
    volumes:
      - ./volume:/nexus-data
    expose:
      - 8081
      - 8082
      - 8083
      #ports:
      #- '8081:8081'
      #- '8082:8082'
      #- '8083:8083'
    restart: always
  nginx:
    image: novinrepo:8082/docker/nginx:1.18
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/secrets:/etc/nginx/ssl/
    restart: always
